spring.application.name=tarefasapi

spring.datasource.url=jdbc:postgresql://dpg-d7jmkk9f9bms73fveq70-a:5432/tarefas-api-db
spring.datasource.username=tarefas_api_db_user
spring.datasource.password=Y2l2wd7bsG3GGiTiFTEpCLZCePqIbMwm

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
